baseURL: "https://adrienguillement.fr/"
languageCode: "fr-Fr"
title: "Adrien Guillement"
enableRobotsTXT: true
theme: paper

params:
  color: 'gray'
  github: 'aguillement'

menu: 
  main:
  - identifier: about
    name: A propros
    url: /about/
    weight: -110
  - name: Posts
    post: <span class='alert'>New!</span>
    url: /posts/
    weight: -100

deployment:
  targets:
    - name: "test-deploy"
      url: "s3://cloud-resume-challenge-aguillement-hugo?region=eu-west-1"
  matchers:
    - pattern: "^.+\\.(js|css|svg|ttf)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
