baseURL: "https://adrienguillement.fr/"
languageCode: "fr-Fr"
title: "Adrien Guillement"
enableRobotsTXT: true
theme: paper

params:
  color: 'gray'
  github: 'aguillement'

menu: 
  main:
  - identifier: about
    name: A propros
    url: /about/
    weight: -110
  - name: Posts
    post: <span class='alert'>New!</span>
    url: /posts/
    weight: -100

deployment:
  targets:
    - name: "S3"
      url: "s3://s3-website-test.terraform.aguillement.com?region=eu-west-1"
      cloudFrontDistributionID: "E2W93717FJT2KB"
  matchers:
    - pattern: "^.+\\.(js|css|svg|ttf)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
